# Generated by Django 5.1.8 on 2025-04-11 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadsapp', '0002_company_sourcetype_agent_activity_files_followups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='followups',
            options={'verbose_name_plural': 'followups'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'messages'},
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='followups',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='followups',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='form',
            name='description',
        ),
        migrations.RemoveField(
            model_name='form',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='form',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='token',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leadsgroup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='leadsgroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='source',
            name='description',
        ),
        migrations.RemoveField(
            model_name='source',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sourcetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sourcetype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadsapp.agent'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadsapp.source'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='leadsapp.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followups',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leadsapp.company'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
