name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Deploy using GitHub Actions HTTPS deployment
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          # Write the private key to a file
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # SSH into the EC2 instance and pull the latest changes
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST '
            cd ~/leads &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart leads
          '
          # Clean up
          rm -f private_key.pem
